Add python37 DU v2
UiPath/ai-customer-scripts pull request #107
Opened 2021-04-12 07:58 UTC by irinel-birsan-uipath

2021-04-12 11:22 UTC, vivekjhauipath requested changes
image tag should be corrected

2021-04-12 11:22 UTC, vivekjhauipath commented on language_version_metadata/Python37_DU__2__metadata.json
> +        "baseImage": "uipathmlcontainerregistry.azurecr.io/aifabric_base_image:NNN-AIF",
replace NNN with 21.4.0

2021-04-13 08:50 UTC, vivekjhauipath approved these changes
LGTM

2021-04-13 08:53 UTC, irinel-birsan-uipath commented
![image](https://user-images.githubusercontent.com/42834544/114525502-d29fc400-9c4e-11eb-927a-73c0703ba53b.png)

2021-04-13 13:28 UTC, adeepsri approved these changes
LGTM

2021-04-15 04:28 UTC, mohitseth-nitrr commented
@irinel-birsan-uipath Can you attach the ticket here ? I want to understand what are these changes for and why do they belong to separate folder on ai-customer-scripts instead of metadata folder.

2021-04-15 04:50 UTC, mohitseth-nitrr commented
> 
> 
> @irinel-birsan-uipath Can you attach the ticket here ? I want to understand what are these changes for and why do they belong to separate folder on ai-customer-scripts instead of metadata folder.

confirmed with @adeepsri @vivekjhauipath  ... looks like this is something new

2021-04-15 04:50 UTC, merged