[AIFBR-10186] add computer vision 21.2 model with latest baseimage
UiPath/ai-customer-scripts pull request #130
Opened 2021-09-16 09:07 UTC by vivekjhauipath

2021-09-16 11:51 UTC, avin45h approved these changes

2021-09-16 13:19 UTC, SahilChaudhary25 requested changes

2021-09-16 13:19 UTC, SahilChaudhary25 commented on language_version_metadata/Python36_CV__2__metadata.json
> +        "version": 2,
Version should be 3

2021-09-17 09:48 UTC, SahilChaudhary25 approved these changes

2021-09-17 10:27 UTC, merged