added db migration script and migration script for sf migration
UiPath/ai-customer-scripts pull request #133
Opened 2021-09-24 05:54 UTC by aakashuipath

2021-09-24 07:44 UTC, SahilChaudhary25 requested changes

2021-09-24 07:44 UTC, SahilChaudhary25 commented on platform/sfmigration/dbmigrationbcp.bash
> +function update_database_table(){
Please add function docs along with parameter passed description

2021-09-24 07:44 UTC, SahilChaudhary25 commented on platform/sfmigration/dbmigrationbcp.bash
> +export SRC_TRAINER_DB_PASSWORD=$(cat $CREDENTIALS_FILE | jq -r 'select(.SRC_TRAINER_DB_PASSWORD != null) | .SRC_TRAINER_DB_PASSWORD')
Lets break code into smaller function and make it modular with docs

2021-09-24 07:44 UTC, SahilChaudhary25 commented on platform/sfmigration/input.json
> +{
platform/sfmigration/input.json -> platform/sfmigration/sampleinput.json
Please star sdding readme file with detailed steps

2021-09-24 07:44 UTC, SahilChaudhary25 commented on platform/sfmigration/mastermigrationscript.bash
> +This scipt will export all data stored in blob storage from target environments.
Looks wrong

2021-09-29 18:08 UTC, aakashuipath commented on platform/sfmigration/mastermigrationscript.bash
> +This scipt will export all data stored in blob storage from target environments.
done

2021-09-29 18:09 UTC, aakashuipath commented on platform/sfmigration/dbmigrationbcp.bash
> +function update_database_table(){
done

2022-05-23 06:55 UTC, closed without merging