Storage Checks Before Triggering Onebox Installer
UiPath/ai-customer-scripts pull request #20
Opened 2020-09-13 12:03 UTC by rajivml

* Storage Checks Before Triggering Onebox Installer 
* AIFBR-6039

2020-09-13 12:05 UTC, rajivml commented
![ceph_install_negative_scenario](https://user-images.githubusercontent.com/46923567/93017590-90929f00-f5e7-11ea-9d84-2f2b59ce66d8.PNG)
![ceph_install_positive_scenario](https://user-images.githubusercontent.com/46923567/93017592-925c6280-f5e7-11ea-86be-c62be33cc9dc.PNG)

2020-09-15 04:57 UTC, mohitseth-nitrr commented on platform/scripts/os-check.sh
> +if [[ ("${OS}" != "Ubuntu") && ("${OS}" != "Red Hat Enterprise Linux Server") ]];
Lets make a list here so that modification is easier. We are currently testing centos 7.6 as well

2020-09-15 04:58 UTC, mohitseth-nitrr commented on platform/scripts/os-check.sh
> +#!/bin/bash
we need rhel version check as well ... we support 7.4+ and below 8

2020-09-15 05:05 UTC, mohitseth-nitrr commented on platform/scripts/lvm-check.sh
> +LVM_VERSION=$( lvm version | grep "LVM version" )
what do we use lvm for in our installer ?

2020-09-15 05:06 UTC, mohitseth-nitrr commented on platform/scripts/install-kurl.sh
> +#!/bin/bash
This is dev installation command ... lets not push it to master

2020-09-15 05:07 UTC, mohitseth-nitrr commented on platform/scripts/create-serviceaccount.sh
> +chmod +r /etc/kubernetes/admin.conf
Can we check the existence of this file before doing this operation ?

2020-09-15 05:08 UTC, mohitseth-nitrr requested changes
changes needed

2020-09-15 05:10 UTC, mohitseth-nitrr commented on platform/scripts/storage-check.sh
> +      then
I think we recommend 256G minimum. Please check preflight checks for exact messages.

2020-09-22 04:42 UTC, closed without merging