AIFBR-12442 : Delete OOB package version
UiPath/ai-customer-scripts pull request #208
Opened 2022-09-26 04:32 UTC by vaibhavs-uipath

2022-09-26 04:35 UTC, vivekjhauipath commented on mlpackage/deleteoob/input.json
> +	"dbConnection": "sfdev3014441-a0d04dcc-sql.database.windows.net",
remove these values, instead put <<db connection string>> etc.

2022-09-26 04:37 UTC, vivekjhauipath commented on mlpackage/deleteoob/deleteoobpackageversion.sh
> +  echo $contentUri
nit: with dockerImage support this field can be null, in which case just delete entry and no zip file

2022-09-26 04:39 UTC, vivekjhauipath requested changes
1. Remove creds etc from commit. Squash so that it doesn't appear in history.
2. Delete package if no more versions present. Else bad UX
3. Check with PMs if we need to delete cloned versions based on this version too? Could be an enhancement

2022-09-27 08:38 UTC, vaibhavs-uipath commented
> 1. Remove creds etc from commit. Squash so that it doesn't appear in history.
> 2. Delete package if no more versions present. Else bad UX
> 3. Check with PMs if we need to delete cloned versions based on this version too? Could be an enhancement

@vivekjhauipath  These are done,please check.

2022-09-27 08:55 UTC, pramod-rao-uipath approved these changes
LGTM

2022-09-28 04:57 UTC, vnaren23 approved these changes

2022-09-28 04:59 UTC, vivekjhauipath approved these changes
LGTM.
Though we aren't handling cloned version cascading delete, but we can probably do that from UI, so should be fine.

2022-09-28 04:59 UTC, vivekjhauipath commented
> > 1. Remove creds etc from commit. Squash so that it doesn't appear in history.
> > 2. Delete package if no more versions present. Else bad UX
> > 3. Check with PMs if we need to delete cloned versions based on this version too? Could be an enhancement
> 
> @vivekjhauipath These are done,please check.

3rd is not done.

2022-09-28 05:01 UTC, vivekjhauipath commented
Also, @vaibhavs-uipath minor enhancement could be to support customVersion also.

2022-09-28 05:01 UTC, merged