Add new NER version
UiPath/ai-customer-scripts pull request #334
Opened 2024-11-04 15:13 UTC by andznui

fixes https://uipath.atlassian.net/browse/ACTV-75868

2024-11-04 18:29 UTC, irinel-birsan-uipath approved these changes

2024-11-04 18:30 UTC, irinel-birsan-uipath requested changes
Please modify the content uri

2024-11-04 18:30 UTC, irinel-birsan-uipath commented on metadata/CustomNamedEntityRecognition__10__metadata.json
> +    "contentUri": "https://<placeholder-url>/publicmodels/AIC/CustomNamedEntityRecognition/9/ner_package.zip"
Lets create the folder named 10: https://<placeholder-url>/publicmodels/AIC/CustomNamedEntityRecognition/10/ner_package.zip

2024-11-04 18:56 UTC, irinel-birsan-uipath approved these changes

2024-11-05 07:25 UTC, sstefanov78 approved these changes

2024-11-05 10:19 UTC, merged