Delete active trainings jobs if any after restore
UiPath/ai-customer-scripts pull request #95
Opened 2021-03-18 14:41 UTC by SahilChaudhary25

2021-03-19 02:40 UTC, vivekjhauipath commented on platform/onebox/backup_and_restore/clusterResources/import.sh
> +      kubectl delete jobs --all -n ${NAMESPACES[ns]}
this will delete jobs associated with cronjobs too. Filter it on DM and training-ns

2021-03-19 02:40 UTC, vivekjhauipath requested changes
Minor filtering needed

2021-03-23 17:01 UTC, vivekjhauipath approved these changes
LGTM

2021-03-24 05:52 UTC, Mdirfan6 approved these changes
lgtm

2021-03-24 05:52 UTC, merged